name: velora
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

# Flutter SDK version
environment:
  sdk: '>=3.5.4 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.1
  dash_chat_2: ^0.0.21
  http: ^1.2.2
  flutter_dotenv: ^5.0.2
  firebase_core: ^3.8.0
  form_field_validator: ^1.1.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  intl_phone_number_input: ^0.7.4
  flutter_launcher_icons: ^0.14.1
  flutter_staggered_animations: ^1.1.1
  flutter_inappwebview: ^6.1.5
  google_fonts: ^6.2.1

# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/velora_logo.png"
  min_sdk_android: 23 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/velora_logo.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/images/velora_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/velora_logo.png"

# Flutter-specific settings
flutter:
  uses-material-design: true

  # Adding assets
  assets:
    - assets/images/splash_image.png
    - assets/images/home_screen/header/sandwich.png
    - assets/images/home_screen/header/be_mindful.png
    - assets/images/home_screen/header/bell.png
    - assets/images/home_screen/body/cyan.png
    - assets/images/home_screen/body/emojis.png
    - assets/images/home_screen/body/grey.png
    - assets/images/home_screen/body/purple.png
    - assets/images/home_screen/body/video.png
    - assets/images/home_screen/body/daily.png
    - assets/images/home_screen/body/feeling.png
    - assets/images/home_screen/body/healing.png
    - assets/images/home_screen/body/red.png
    - assets/images/velora_logo.png
    - .env
