name: velora
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

# Flutter SDK version
environment:
  sdk: '>=3.5.4 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.1
  dash_chat_2: ^0.0.21
  http: ^1.2.2
  flutter_dotenv: ^5.0.2
  firebase_core: ^3.8.0
  form_field_validator: ^1.1.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  intl_phone_number_input: ^0.7.4
  flutter_launcher_icons: ^0.14.1
  flutter_staggered_animations: ^1.1.1
  flutter_inappwebview: ^6.1.5
  google_fonts: ^6.2.1
  intl: ^0.19.0
  flutter_charts: ^0.5.2
  fl_chart: ^0.69.0
  pie_chart: ^5.4.0
  open_filex: ^4.5.0
  path_provider: ^2.1.5
  printing: ^5.13.4
  pdf: ^3.11.1
  screenshot: ^3.0.0
  file_picker: ^8.1.4
  flutter_email_sender: ^6.0.3
  mailer: ^6.2.0

# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter-specific settings
flutter:
  uses-material-design: true

  # Adding assets
  assets:
    - assets/fonts/Roboto-Regular.ttf
    - assets/images/splash_image.png
    - assets/images/home_screen/header/sandwich.png
    - assets/images/home_screen/header/be_mindful.png
    - assets/images/home_screen/header/bell.png
    - assets/images/home_screen/body/cyan.png
    - assets/images/home_screen/body/emojis.png
    - assets/images/home_screen/body/grey.png
    - assets/images/home_screen/body/purple.png
    - assets/images/home_screen/body/video.png
    - assets/images/home_screen/body/daily.png
    - assets/images/home_screen/body/feeling.png
    - assets/images/home_screen/body/healing.png
    - assets/images/home_screen/body/red.png
    - assets/images/velora_logo.png
    - assets/images/self-care.jpg
    - assets/images/doctor.png
    - .env
