name: velora
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

# Flutter SDK version
environment:
  sdk: '>=3.5.4 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.1

# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter-specific settings
flutter:
  uses-material-design: true

  # Adding assets
  assets:
    - assets/images/splash_image.png
    - assets/images/home_screen/header/sandwich.png
    - assets/images/home_screen/header/be_mindful.png
    - assets/images/home_screen/header/bell.png
    - assets/images/home_screen/body/cyan.png
    - assets/images/home_screen/body/emojis.png
    - assets/images/home_screen/body/grey.png
    - assets/images/home_screen/body/purple.png
    - assets/images/home_screen/body/video.png
    - assets/images/home_screen/body/daily.png
    - assets/images/home_screen/body/feeling.png
    - assets/images/home_screen/body/healing.png
    - assets/images/home_screen/body/red.png
